name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'We''re glad you find this project helpful. We''ll try to address this issue ASAP. You can vist https://solothought.com to know recent features. Don''t forget to star this repo.'
